apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      color: blue
  template:
    metadata:
      labels:
        app: myapp
        color: blue
    spec:
      containers:
        - name: myapp-container
          image: placeholder:latest # Replaced by Jenkins
          ports:
            - containerPort: 8080
